name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      release_description:
        description: 'Enter description of release (max 16 characters)'
        required: true
        default: 'Enter Value'
      ami_tag_name:
        description: 'Enter AMI tag'
        required: true
        default: 'Enter ami tag'
      environment:
        description: 'Enter environment ("Prod deploy" or "Crm deploy")'
        required: true
        default: 'Enter Value'


jobs:
  build:
    if: github.event.inputs.environment == 'Prod deploy'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: echo "hello"
  trigger: 
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: sheoranankit
          repo: janusdeployments
          github_token: ${{ secrets.ACTIONS_TOKEN }}
          workflow_file_name: python-package-conda.yml
          ref: main
          wait_interval: 2
          client_payload: '{}'
          propagate_failure: false
          trigger_workflow: true
          wait_workflow: true
