name: Python Package using Conda

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for other checks to succeed
        uses: lewagon/wait-on-check-action@v1.3.1
        with:
          ref: master
          check-name: build
          repo-token: ${{ secrets.ACTIONS_TOKEN }}
          wait-interval: 10
          allowed-conclusions: success
  build-linux:
    needs: [publish]
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo "hello"
